/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\models\classicmusclecar.glb 
Author: Lexyc16 (https://sketchfab.com/Lexyc16)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/classic-muscle-car-641efc889e5f4543bae51d0922e6f4b3
Title: Classic Muscle car
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/classicmusclecar.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={[1, 0.848, 5.952]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.Material} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Object_7.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Object_9.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Object_10.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Object_11.geometry} material={materials['Material.008']} />
      </group>
      <group position={[-2.234, -0.625, 3.816]}>
        <mesh geometry={nodes.Object_13.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_14.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Object_15.geometry} material={materials['Material.007']} />
      </group>
      <group position={[2.234, -0.531, -3.075]}>
        <mesh geometry={nodes.Object_17.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_18.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Object_19.geometry} material={materials['Material.007']} />
      </group>
      <group position={[2.234, -0.625, 3.816]}>
        <mesh geometry={nodes.Object_21.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_22.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Object_23.geometry} material={materials['Material.007']} />
      </group>
      <group position={[-2.234, -0.531, -3.075]}>
        <mesh geometry={nodes.Object_25.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_26.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Object_27.geometry} material={materials['Material.007']} />
      </group>
    </group>
  )
}

useGLTF.preload('/classicmusclecar.glb')
